export const languages = {
  en: {
    settings: "ISRC Finder Dashboard",
    dashboardSubtitle: "Manage your extension settings and monitor activity",
    apiConfiguration: "API Configuration",
    automation: "Automation Settings",
    appearance: "Appearance",
    exportData: "Export & Data",
    notifications: "Notifications",
    backupSync: "Backup & Sync",
    spotifyCredentials: "Spotify Credentials",
    spotifyNote: "Enter your Spotify API credentials from your Spotify Developer Dashboard",
    clientId: "Spotify Client ID",
    enterClientId: "Enter your Spotify Client ID",
    clientSecret: "Spotify Client Secret",
    enterClientSecret: "Enter your Spotify Client Secret",
    tokenDuration: "Token Duration (hours)",
    youtubeApiKey: "YouTube API Key",
    enterYoutubeApiKey: "Enter your YouTube Data API v3 key",
    autoFetch: "Auto-Fetch",
    autoFetchDesc: "Automatically search for ISRC codes",
    clipboardMonitor: "Clipboard Monitor",
    clipboardMonitorDesc: "Scan clipboard for music links",
    desktopNotifications: "Desktop Notifications",
    desktopNotificationsDesc: "Show system notifications",
    autoExportDesc: "Automatically export search results",
    saveChanges: "Save Configuration",
    clearAll: "Reset All Settings",
    testConnection: "Test Connection",
    success: "Settings saved successfully",
    error: "Error saving settings",
    cleared: "All settings cleared",
    required: "All fields are required",
    connectionSuccess: "Spotify connection successful! 🎉",
    connectionFailed: "Connection failed",
    spotifyClientIdRequired: "Spotify Client ID is required",
    spotifyClientSecretRequired: "Spotify Client Secret is required",
    youtubeApiKeyRequired: "YouTube API Key is required",
    invalidSpotifyClientId: "Invalid Spotify Client ID",
    invalidSpotifyClientSecret: "Invalid Spotify Client Secret",
    errorLoadingSettings: "Error loading settings",
    spotifyCredentialsExpired: "Spotify credentials have expired",
    failedToInitializeSettings: "Failed to initialize settings",
    errorSavingSettings: "Error saving settings",
    failedToSaveSettings: "Failed to save settings",
    errorClearingSettings: "Error clearing settings",
    allSettingsCleared: "All settings cleared",
    failedToClearSettings: "Failed to clear settings",
    spotifyConnectionSuccess: "Spotify connection successful! 🎉",
    connectionTestSuccess: "Connection test successful",
    connectionTestFailed: "Connection test failed",
    advancedSettings: "Advanced Settings",
    darkModeEnabled: "Dark mode enabled",
    lightModeEnabled: "Light mode enabled"
  },
  sq: {
    settings: "Paneli i ISRC Finder",
    dashboardSubtitle: "Menaxhoni cilësimet e zgjatjes dhe monitoroni aktivitetin",
    apiConfiguration: "Konfigurimi i API",
    automation: "Cilësimet e Automatizimit",
    appearance: "Pamja",
    exportData: "Eksporti & të Dhënat",
    notifications: "Njoftimet",
    backupSync: "Backup & Sync",
    spotifyCredentials: "Kredencialet e Spotify",
    spotifyNote: "Vendosni kredencialet tuaja të API Spotify nga Paneli i Zhvilluesve Spotify",
    clientId: "ID e Klientit Spotify",
    enterClientId: "Vendosni ID-në tuaj të Klientit Spotify",
    clientSecret: "Sekreti i Klientit Spotify",
    enterClientSecret: "Vendosni Sekretin tuaj të Klientit Spotify",
    tokenDuration: "Kohëzgjatja e Token (orë)",
    youtubeApiKey: "Çelësi API i YouTube",
    enterYoutubeApiKey: "Vendosni çelësin tuaj YouTube Data API v3",
    autoFetch: "Auto-Fetch",
    autoFetchDesc: "Kërko automatikisht për kode ISRC",
    clipboardMonitor: "Monitorimi i Clipboard",
    clipboardMonitorDesc: "Skanoni clipboard për lidhje muzike",
    desktopNotifications: "Njoftimet e Desktop",
    desktopNotificationsDesc: "Shfaq njoftime sistemi",
    autoExportDesc: "Eksporto automatikisht rezultatet e kërkimit",
    saveChanges: "Ruaj Konfigurimin",
    clearAll: "Rivendos të Gjitha Cilësimet",
    testConnection: "Testo Lidhjen",
    success: "Cilësimet u ruajtën me sukses",
    error: "Gabim në ruajtjen e cilësimeve",
    cleared: "Të gjitha cilësimet u pastruan",
    required: "Të gjitha fushat janë të detyrueshme",
    connectionSuccess: "Lidhja me Spotify u krye me sukses! 🎉",
    connectionFailed: "Lidhja dështoi",
    spotifyClientIdRequired: "ID e Klientit Spotify është e detyrueshme",
    spotifyClientSecretRequired: "Sekreti i Klientit Spotify është i detyrueshëm",
    youtubeApiKeyRequired: "Çelësi API i YouTube është i detyrueshëm",
    invalidSpotifyClientId: "ID e pavlefshme e Klientit Spotify",
    invalidSpotifyClientSecret: "Sekret i pavlefshëm i Klientit Spotify",
    errorLoadingSettings: "Gabim në ngarkimin e cilësimeve",
    spotifyCredentialsExpired: "Kredencialet e Spotify kanë skaduar",
    failedToInitializeSettings: "Dështoi inicializimi i cilësimeve",
    errorSavingSettings: "Gabim në ruajtjen e cilësimeve",
    failedToSaveSettings: "Dështoi ruajtja e cilësimeve",
    errorClearingSettings: "Gabim në pastrimin e cilësimeve",
    allSettingsCleared: "Të gjitha cilësimet u pastruan",
    failedToClearSettings: "Dështoi pastrimi i cilësimeve",
    spotifyConnectionSuccess: "Lidhja me Spotify u krye me sukses! 🎉",
    connectionTestSuccess: "Testi i lidhjes u krye me sukses",
    connectionTestFailed: "Testi i lidhjes dështoi",
    advancedSettings: "Cilësimet e Avancuara",
    darkModeEnabled: "Modaliteti i errët u aktivizua",
    lightModeEnabled: "Modaliteti i dritës u aktivizua"
  },
  de: {
    settings: "ISRC Finder Dashboard",
    dashboardSubtitle: "Verwalten Sie Ihre Erweiterungseinstellungen und überwachen Sie die Aktivität",
    apiConfiguration: "API-Konfiguration",
    automation: "Automatisierungseinstellungen",
    appearance: "Erscheinungsbild",
    exportData: "Export & Daten",
    notifications: "Benachrichtigungen",
    backupSync: "Backup & Synchronisation",
    spotifyCredentials: "Spotify-Anmeldedaten",
    spotifyNote: "Geben Sie Ihre Spotify-API-Anmeldedaten aus Ihrem Spotify Developer Dashboard ein",
    clientId: "Spotify Client-ID",
    enterClientId: "Geben Sie Ihre Spotify Client-ID ein",
    clientSecret: "Spotify Client-Geheimnis",
    enterClientSecret: "Geben Sie Ihr Spotify Client-Geheimnis ein",
    tokenDuration: "Token-Dauer (Stunden)",
    youtubeApiKey: "YouTube API-Schlüssel",
    enterYoutubeApiKey: "Geben Sie Ihren YouTube Data API v3-Schlüssel ein",
    autoFetch: "Auto-Fetch",
    autoFetchDesc: "Automatisch nach ISRC-Codes suchen",
    clipboardMonitor: "Zwischenablage-Monitor",
    clipboardMonitorDesc: "Zwischenablage nach Musik-Links durchsuchen",
    desktopNotifications: "Desktop-Benachrichtigungen",
    desktopNotificationsDesc: "Systembenachrichtigungen anzeigen",
    autoExportDesc: "Suchergebnisse automatisch exportieren",
    saveChanges: "Konfiguration speichern",
    clearAll: "Alle Einstellungen zurücksetzen",
    testConnection: "Verbindung testen",
    success: "Einstellungen erfolgreich gespeichert",
    error: "Fehler beim Speichern der Einstellungen",
    cleared: "Alle Einstellungen gelöscht",
    required: "Alle Felder sind erforderlich",
    connectionSuccess: "Spotify-Verbindung erfolgreich! 🎉",
    connectionFailed: "Verbindung fehlgeschlagen",
    spotifyClientIdRequired: "Spotify Client-ID ist erforderlich",
    spotifyClientSecretRequired: "Spotify Client-Geheimnis ist erforderlich",
    youtubeApiKeyRequired: "YouTube API-Schlüssel ist erforderlich",
    invalidSpotifyClientId: "Ungültige Spotify Client-ID",
    invalidSpotifyClientSecret: "Ungültiges Spotify Client-Geheimnis",
    errorLoadingSettings: "Fehler beim Laden der Einstellungen",
    spotifyCredentialsExpired: "Spotify-Anmeldedaten sind abgelaufen",
    failedToInitializeSettings: "Fehler beim Initialisieren der Einstellungen",
    errorSavingSettings: "Fehler beim Speichern der Einstellungen",
    success: "Einstellungen erfolgreich gespeichert",
    failedToSaveSettings: "Fehler beim Speichern der Einstellungen",
    errorClearingSettings: "Fehler beim Löschen der Einstellungen",
    allSettingsCleared: "Alle Einstellungen gelöscht",
    failedToClearSettings: "Fehler beim Löschen der Einstellungen",
    spotifyConnectionSuccess: "Spotify-Verbindung erfolgreich! 🎉",
    connectionTestSuccess: "Verbindungstest erfolgreich",
    connectionTestFailed: "Verbindungstest fehlgeschlagen",
    advancedSettings: "Erweiterte Einstellungen",
    darkModeEnabled: "Dunkler Modus aktiviert",
    lightModeEnabled: "Heller Modus aktiviert"
  }
};

export const availableLanguages = [
  {
    code: 'en',
    name: 'English',
    flag: '🇬🇧'
  },
  {
    code: 'sq',
    name: 'Shqip',
    flag: '🇦🇱'
  },
  {
    code: 'de',
    name: 'Deutsch',
    flag: '🇩🇪'
  }
];

export function getLanguageName(code) {
  const language = availableLanguages.find(lang => lang.code === code);
  return language ? language.name : 'Unknown';
}

export function getLanguageFlag(code) {
  const language = availableLanguages.find(lang => lang.code === code);
  return language ? language.flag : '🌐';
}

export function isValidLanguage(code) {
  return availableLanguages.some(lang => lang.code === code);
}